trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '22.x'
  DEPLOY_PATH: '/www/wwwroot/lulidong.com'

stages:
  - stage: BuildAndDeploy
    displayName: Build and Deploy Static Site
    jobs:
      - job: build
        displayName: Build Job
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '$(NODE_VERSION)'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'Install Dependencies'

          - script: |
              npm run build
            displayName: 'Build Project'

          - script: |
              sudo rm -rf $(DEPLOY_PATH)/*
              sudo cp -r out/* $(DEPLOY_PATH)/
            displayName: 'Copy Build Output to Deploy Path'